// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: renderer/v1/renderer.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenderLayerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Global image dimensions
	Width  int32 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height int32 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	// Logical Layer definition
	LayerName        string   `protobuf:"bytes,3,opt,name=layer_name,json=layerName,proto3" json:"layer_name,omitempty"`
	IncludeObjectIds []uint32 `protobuf:"varint,4,rep,packed,name=include_object_ids,json=includeObjectIds,proto3" json:"include_object_ids,omitempty"` // IDs of meshes belonging to this layer
	// Quality settings
	SamplesPerPixel int32  `protobuf:"varint,5,opt,name=samples_per_pixel,json=samplesPerPixel,proto3" json:"samples_per_pixel,omitempty"`
	MaxDepth        int32  `protobuf:"varint,6,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	Seed            uint32 `protobuf:"varint,7,opt,name=seed,proto3" json:"seed,omitempty"` // To ensure deterministic sampling across the layer
	// Worker-level threading (how many internal tiles to run in parallel)
	NumThreads int32 `protobuf:"varint,8,opt,name=num_threads,json=numThreads,proto3" json:"num_threads,omitempty"`
	// Scene context
	SceneFile string `protobuf:"bytes,9,opt,name=scene_file,json=sceneFile,proto3" json:"scene_file,omitempty"`
	// Bucket destination
	OutputTargetUri string `protobuf:"bytes,10,opt,name=output_target_uri,json=outputTargetUri,proto3" json:"output_target_uri,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RenderLayerRequest) Reset() {
	*x = RenderLayerRequest{}
	mi := &file_renderer_v1_renderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderLayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderLayerRequest) ProtoMessage() {}

func (x *RenderLayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_renderer_v1_renderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderLayerRequest.ProtoReflect.Descriptor instead.
func (*RenderLayerRequest) Descriptor() ([]byte, []int) {
	return file_renderer_v1_renderer_proto_rawDescGZIP(), []int{0}
}

func (x *RenderLayerRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *RenderLayerRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *RenderLayerRequest) GetLayerName() string {
	if x != nil {
		return x.LayerName
	}
	return ""
}

func (x *RenderLayerRequest) GetIncludeObjectIds() []uint32 {
	if x != nil {
		return x.IncludeObjectIds
	}
	return nil
}

func (x *RenderLayerRequest) GetSamplesPerPixel() int32 {
	if x != nil {
		return x.SamplesPerPixel
	}
	return 0
}

func (x *RenderLayerRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *RenderLayerRequest) GetSeed() uint32 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *RenderLayerRequest) GetNumThreads() int32 {
	if x != nil {
		return x.NumThreads
	}
	return 0
}

func (x *RenderLayerRequest) GetSceneFile() string {
	if x != nil {
		return x.SceneFile
	}
	return ""
}

func (x *RenderLayerRequest) GetOutputTargetUri() string {
	if x != nil {
		return x.OutputTargetUri
	}
	return ""
}

type RenderLayerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success flag
	Success  bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	// Confirmation of where file was actually saved
	OutputUri string `protobuf:"bytes,3,opt,name=output_uri,json=outputUri,proto3" json:"output_uri,omitempty"`
	// Stats for the coordinator
	RenderTimeMs  int64 `protobuf:"varint,4,opt,name=render_time_ms,json=renderTimeMs,proto3" json:"render_time_ms,omitempty"`
	TotalSamples  int64 `protobuf:"varint,5,opt,name=total_samples,json=totalSamples,proto3" json:"total_samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderLayerResponse) Reset() {
	*x = RenderLayerResponse{}
	mi := &file_renderer_v1_renderer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderLayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderLayerResponse) ProtoMessage() {}

func (x *RenderLayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_renderer_v1_renderer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderLayerResponse.ProtoReflect.Descriptor instead.
func (*RenderLayerResponse) Descriptor() ([]byte, []int) {
	return file_renderer_v1_renderer_proto_rawDescGZIP(), []int{1}
}

func (x *RenderLayerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RenderLayerResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *RenderLayerResponse) GetOutputUri() string {
	if x != nil {
		return x.OutputUri
	}
	return ""
}

func (x *RenderLayerResponse) GetRenderTimeMs() int64 {
	if x != nil {
		return x.RenderTimeMs
	}
	return 0
}

func (x *RenderLayerResponse) GetTotalSamples() int64 {
	if x != nil {
		return x.TotalSamples
	}
	return 0
}

var File_renderer_v1_renderer_proto protoreflect.FileDescriptor

const file_renderer_v1_renderer_proto_rawDesc = "" +
	"\n" +
	"\x1arenderer/v1/renderer.proto\x12\vrenderer.v1\"\xd8\x02\n" +
	"\x12RenderLayerRequest\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x1d\n" +
	"\n" +
	"layer_name\x18\x03 \x01(\tR\tlayerName\x12,\n" +
	"\x12include_object_ids\x18\x04 \x03(\rR\x10includeObjectIds\x12*\n" +
	"\x11samples_per_pixel\x18\x05 \x01(\x05R\x0fsamplesPerPixel\x12\x1b\n" +
	"\tmax_depth\x18\x06 \x01(\x05R\bmaxDepth\x12\x12\n" +
	"\x04seed\x18\a \x01(\rR\x04seed\x12\x1f\n" +
	"\vnum_threads\x18\b \x01(\x05R\n" +
	"numThreads\x12\x1d\n" +
	"\n" +
	"scene_file\x18\t \x01(\tR\tsceneFile\x12*\n" +
	"\x11output_target_uri\x18\n" +
	" \x01(\tR\x0foutputTargetUri\"\xb6\x01\n" +
	"\x13RenderLayerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x1d\n" +
	"\n" +
	"output_uri\x18\x03 \x01(\tR\toutputUri\x12$\n" +
	"\x0erender_time_ms\x18\x04 \x01(\x03R\frenderTimeMs\x12#\n" +
	"\rtotal_samples\x18\x05 \x01(\x03R\ftotalSamples2c\n" +
	"\x0fRendererService\x12P\n" +
	"\vRenderLayer\x12\x1f.renderer.v1.RenderLayerRequest\x1a .renderer.v1.RenderLayerResponseB\x19Z\x17./api/proto/renderer/v1b\x06proto3"

var (
	file_renderer_v1_renderer_proto_rawDescOnce sync.Once
	file_renderer_v1_renderer_proto_rawDescData []byte
)

func file_renderer_v1_renderer_proto_rawDescGZIP() []byte {
	file_renderer_v1_renderer_proto_rawDescOnce.Do(func() {
		file_renderer_v1_renderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_renderer_v1_renderer_proto_rawDesc), len(file_renderer_v1_renderer_proto_rawDesc)))
	})
	return file_renderer_v1_renderer_proto_rawDescData
}

var file_renderer_v1_renderer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_renderer_v1_renderer_proto_goTypes = []any{
	(*RenderLayerRequest)(nil),  // 0: renderer.v1.RenderLayerRequest
	(*RenderLayerResponse)(nil), // 1: renderer.v1.RenderLayerResponse
}
var file_renderer_v1_renderer_proto_depIdxs = []int32{
	0, // 0: renderer.v1.RendererService.RenderLayer:input_type -> renderer.v1.RenderLayerRequest
	1, // 1: renderer.v1.RendererService.RenderLayer:output_type -> renderer.v1.RenderLayerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_renderer_v1_renderer_proto_init() }
func file_renderer_v1_renderer_proto_init() {
	if File_renderer_v1_renderer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_renderer_v1_renderer_proto_rawDesc), len(file_renderer_v1_renderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_renderer_v1_renderer_proto_goTypes,
		DependencyIndexes: file_renderer_v1_renderer_proto_depIdxs,
		MessageInfos:      file_renderer_v1_renderer_proto_msgTypes,
	}.Build()
	File_renderer_v1_renderer_proto = out.File
	file_renderer_v1_renderer_proto_goTypes = nil
	file_renderer_v1_renderer_proto_depIdxs = nil
}
