// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: renderer/v1/renderer.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RendererService_RenderLayer_FullMethodName = "/renderer.v1.RendererService/RenderLayer"
)

// RendererServiceClient is the client API for RendererService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RendererService provides an API for rendering an image
type RendererServiceClient interface {
	// Tells worker to render an entire logical layer (e.g., "Background" or "Characters")
	RenderLayer(ctx context.Context, in *RenderLayerRequest, opts ...grpc.CallOption) (*RenderLayerResponse, error)
}

type rendererServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRendererServiceClient(cc grpc.ClientConnInterface) RendererServiceClient {
	return &rendererServiceClient{cc}
}

func (c *rendererServiceClient) RenderLayer(ctx context.Context, in *RenderLayerRequest, opts ...grpc.CallOption) (*RenderLayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderLayerResponse)
	err := c.cc.Invoke(ctx, RendererService_RenderLayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RendererServiceServer is the server API for RendererService service.
// All implementations must embed UnimplementedRendererServiceServer
// for forward compatibility.
//
// RendererService provides an API for rendering an image
type RendererServiceServer interface {
	// Tells worker to render an entire logical layer (e.g., "Background" or "Characters")
	RenderLayer(context.Context, *RenderLayerRequest) (*RenderLayerResponse, error)
	mustEmbedUnimplementedRendererServiceServer()
}

// UnimplementedRendererServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRendererServiceServer struct{}

func (UnimplementedRendererServiceServer) RenderLayer(context.Context, *RenderLayerRequest) (*RenderLayerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderLayer not implemented")
}
func (UnimplementedRendererServiceServer) mustEmbedUnimplementedRendererServiceServer() {}
func (UnimplementedRendererServiceServer) testEmbeddedByValue()                         {}

// UnsafeRendererServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RendererServiceServer will
// result in compilation errors.
type UnsafeRendererServiceServer interface {
	mustEmbedUnimplementedRendererServiceServer()
}

func RegisterRendererServiceServer(s grpc.ServiceRegistrar, srv RendererServiceServer) {
	// If the following call panics, it indicates UnimplementedRendererServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RendererService_ServiceDesc, srv)
}

func _RendererService_RenderLayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderLayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendererServiceServer).RenderLayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RendererService_RenderLayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendererServiceServer).RenderLayer(ctx, req.(*RenderLayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RendererService_ServiceDesc is the grpc.ServiceDesc for RendererService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RendererService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "renderer.v1.RendererService",
	HandlerType: (*RendererServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RenderLayer",
			Handler:    _RendererService_RenderLayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "renderer/v1/renderer.proto",
}
