// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: compositor/v1/compositor.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeepLayerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LayerName     string                 `protobuf:"bytes,1,opt,name=layer_name,json=layerName,proto3" json:"layer_name,omitempty"`
	InputUri      string                 `protobuf:"bytes,2,opt,name=input_uri,json=inputUri,proto3" json:"input_uri,omitempty"` // URI to the .exr file for this layer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepLayerInput) Reset() {
	*x = DeepLayerInput{}
	mi := &file_compositor_v1_compositor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepLayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepLayerInput) ProtoMessage() {}

func (x *DeepLayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_compositor_v1_compositor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepLayerInput.ProtoReflect.Descriptor instead.
func (*DeepLayerInput) Descriptor() ([]byte, []int) {
	return file_compositor_v1_compositor_proto_rawDescGZIP(), []int{0}
}

func (x *DeepLayerInput) GetLayerName() string {
	if x != nil {
		return x.LayerName
	}
	return ""
}

func (x *DeepLayerInput) GetInputUri() string {
	if x != nil {
		return x.InputUri
	}
	return ""
}

type CompositeDeepLayersRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Layers []*DeepLayerInput      `protobuf:"bytes,1,rep,name=layers,proto3" json:"layers,omitempty"`
	// If true, the compositor flattens and produces a standard RGBA EXR/PNG.
	// If false, it produces a merged Deep EXR.
	FlattenOutput bool `protobuf:"varint,2,opt,name=flatten_output,json=flattenOutput,proto3" json:"flatten_output,omitempty"`
	// Destination URI for the composited result
	OutputTargetUri string `protobuf:"bytes,3,opt,name=output_target_uri,json=outputTargetUri,proto3" json:"output_target_uri,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompositeDeepLayersRequest) Reset() {
	*x = CompositeDeepLayersRequest{}
	mi := &file_compositor_v1_compositor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeDeepLayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeDeepLayersRequest) ProtoMessage() {}

func (x *CompositeDeepLayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compositor_v1_compositor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeDeepLayersRequest.ProtoReflect.Descriptor instead.
func (*CompositeDeepLayersRequest) Descriptor() ([]byte, []int) {
	return file_compositor_v1_compositor_proto_rawDescGZIP(), []int{1}
}

func (x *CompositeDeepLayersRequest) GetLayers() []*DeepLayerInput {
	if x != nil {
		return x.Layers
	}
	return nil
}

func (x *CompositeDeepLayersRequest) GetFlattenOutput() bool {
	if x != nil {
		return x.FlattenOutput
	}
	return false
}

func (x *CompositeDeepLayersRequest) GetOutputTargetUri() string {
	if x != nil {
		return x.OutputTargetUri
	}
	return ""
}

type CompositeDeepLayersResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Success  bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	// URI of the final composited image
	OutputUri        string `protobuf:"bytes,3,opt,name=output_uri,json=outputUri,proto3" json:"output_uri,omitempty"`
	ProcessingTimeMs int64  `protobuf:"varint,4,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompositeDeepLayersResponse) Reset() {
	*x = CompositeDeepLayersResponse{}
	mi := &file_compositor_v1_compositor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeDeepLayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeDeepLayersResponse) ProtoMessage() {}

func (x *CompositeDeepLayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compositor_v1_compositor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeDeepLayersResponse.ProtoReflect.Descriptor instead.
func (*CompositeDeepLayersResponse) Descriptor() ([]byte, []int) {
	return file_compositor_v1_compositor_proto_rawDescGZIP(), []int{2}
}

func (x *CompositeDeepLayersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompositeDeepLayersResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *CompositeDeepLayersResponse) GetOutputUri() string {
	if x != nil {
		return x.OutputUri
	}
	return ""
}

func (x *CompositeDeepLayersResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

var File_compositor_v1_compositor_proto protoreflect.FileDescriptor

const file_compositor_v1_compositor_proto_rawDesc = "" +
	"\n" +
	"\x1ecompositor/v1/compositor.proto\x12\rcompositor.v1\"L\n" +
	"\x0eDeepLayerInput\x12\x1d\n" +
	"\n" +
	"layer_name\x18\x01 \x01(\tR\tlayerName\x12\x1b\n" +
	"\tinput_uri\x18\x02 \x01(\tR\binputUri\"\xa6\x01\n" +
	"\x1aCompositeDeepLayersRequest\x125\n" +
	"\x06layers\x18\x01 \x03(\v2\x1d.compositor.v1.DeepLayerInputR\x06layers\x12%\n" +
	"\x0eflatten_output\x18\x02 \x01(\bR\rflattenOutput\x12*\n" +
	"\x11output_target_uri\x18\x03 \x01(\tR\x0foutputTargetUri\"\xa1\x01\n" +
	"\x1bCompositeDeepLayersResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x1d\n" +
	"\n" +
	"output_uri\x18\x03 \x01(\tR\toutputUri\x12,\n" +
	"\x12processing_time_ms\x18\x04 \x01(\x03R\x10processingTimeMs2\x81\x01\n" +
	"\x11CompositorService\x12l\n" +
	"\x13CompositeDeepLayers\x12).compositor.v1.CompositeDeepLayersRequest\x1a*.compositor.v1.CompositeDeepLayersResponseB\x1bZ\x19./api/proto/compositor/v1b\x06proto3"

var (
	file_compositor_v1_compositor_proto_rawDescOnce sync.Once
	file_compositor_v1_compositor_proto_rawDescData []byte
)

func file_compositor_v1_compositor_proto_rawDescGZIP() []byte {
	file_compositor_v1_compositor_proto_rawDescOnce.Do(func() {
		file_compositor_v1_compositor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_compositor_v1_compositor_proto_rawDesc), len(file_compositor_v1_compositor_proto_rawDesc)))
	})
	return file_compositor_v1_compositor_proto_rawDescData
}

var file_compositor_v1_compositor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_compositor_v1_compositor_proto_goTypes = []any{
	(*DeepLayerInput)(nil),              // 0: compositor.v1.DeepLayerInput
	(*CompositeDeepLayersRequest)(nil),  // 1: compositor.v1.CompositeDeepLayersRequest
	(*CompositeDeepLayersResponse)(nil), // 2: compositor.v1.CompositeDeepLayersResponse
}
var file_compositor_v1_compositor_proto_depIdxs = []int32{
	0, // 0: compositor.v1.CompositeDeepLayersRequest.layers:type_name -> compositor.v1.DeepLayerInput
	1, // 1: compositor.v1.CompositorService.CompositeDeepLayers:input_type -> compositor.v1.CompositeDeepLayersRequest
	2, // 2: compositor.v1.CompositorService.CompositeDeepLayers:output_type -> compositor.v1.CompositeDeepLayersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_compositor_v1_compositor_proto_init() }
func file_compositor_v1_compositor_proto_init() {
	if File_compositor_v1_compositor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compositor_v1_compositor_proto_rawDesc), len(file_compositor_v1_compositor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compositor_v1_compositor_proto_goTypes,
		DependencyIndexes: file_compositor_v1_compositor_proto_depIdxs,
		MessageInfos:      file_compositor_v1_compositor_proto_msgTypes,
	}.Build()
	File_compositor_v1_compositor_proto = out.File
	file_compositor_v1_compositor_proto_goTypes = nil
	file_compositor_v1_compositor_proto_depIdxs = nil
}
