// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: compositor/v1/compositor.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CompositorService_CompositeDeepLayers_FullMethodName = "/compositor.v1.CompositorService/CompositeDeepLayers"
)

// CompositorServiceClient is the client API for CompositorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CompositorService provides an API for merging multiple deep image layers stored in buckets
type CompositorServiceClient interface {
	// Merges multiple deep layers (EXR files) into a single image
	CompositeDeepLayers(ctx context.Context, in *CompositeDeepLayersRequest, opts ...grpc.CallOption) (*CompositeDeepLayersResponse, error)
}

type compositorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompositorServiceClient(cc grpc.ClientConnInterface) CompositorServiceClient {
	return &compositorServiceClient{cc}
}

func (c *compositorServiceClient) CompositeDeepLayers(ctx context.Context, in *CompositeDeepLayersRequest, opts ...grpc.CallOption) (*CompositeDeepLayersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompositeDeepLayersResponse)
	err := c.cc.Invoke(ctx, CompositorService_CompositeDeepLayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompositorServiceServer is the server API for CompositorService service.
// All implementations must embed UnimplementedCompositorServiceServer
// for forward compatibility.
//
// CompositorService provides an API for merging multiple deep image layers stored in buckets
type CompositorServiceServer interface {
	// Merges multiple deep layers (EXR files) into a single image
	CompositeDeepLayers(context.Context, *CompositeDeepLayersRequest) (*CompositeDeepLayersResponse, error)
	mustEmbedUnimplementedCompositorServiceServer()
}

// UnimplementedCompositorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompositorServiceServer struct{}

func (UnimplementedCompositorServiceServer) CompositeDeepLayers(context.Context, *CompositeDeepLayersRequest) (*CompositeDeepLayersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompositeDeepLayers not implemented")
}
func (UnimplementedCompositorServiceServer) mustEmbedUnimplementedCompositorServiceServer() {}
func (UnimplementedCompositorServiceServer) testEmbeddedByValue()                           {}

// UnsafeCompositorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompositorServiceServer will
// result in compilation errors.
type UnsafeCompositorServiceServer interface {
	mustEmbedUnimplementedCompositorServiceServer()
}

func RegisterCompositorServiceServer(s grpc.ServiceRegistrar, srv CompositorServiceServer) {
	// If the following call panics, it indicates UnimplementedCompositorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CompositorService_ServiceDesc, srv)
}

func _CompositorService_CompositeDeepLayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompositeDeepLayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompositorServiceServer).CompositeDeepLayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompositorService_CompositeDeepLayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompositorServiceServer).CompositeDeepLayers(ctx, req.(*CompositeDeepLayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompositorService_ServiceDesc is the grpc.ServiceDesc for CompositorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompositorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "compositor.v1.CompositorService",
	HandlerType: (*CompositorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompositeDeepLayers",
			Handler:    _CompositorService_CompositeDeepLayers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compositor/v1/compositor.proto",
}
