// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/proto/coordinator/v1/coordinator.proto

package coordinatorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoordinatorService_SubmitPipeline_FullMethodName    = "/api.proto.coordinator.v1.CoordinatorService/SubmitPipeline"
	CoordinatorService_GetPipelineStatus_FullMethodName = "/api.proto.coordinator.v1.CoordinatorService/GetPipelineStatus"
	CoordinatorService_CancelPipeline_FullMethodName    = "/api.proto.coordinator.v1.CoordinatorService/CancelPipeline"
)

// CoordinatorServiceClient is the client API for CoordinatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoordinatorService is the external API for the Skewer rendering pipeline.
// Workers communicate directly with Cloud Batch/Workflows, not this service.
type CoordinatorServiceClient interface {
	SubmitPipeline(ctx context.Context, in *SubmitPipelineRequest, opts ...grpc.CallOption) (*SubmitPipelineResponse, error)
	GetPipelineStatus(ctx context.Context, in *GetPipelineStatusRequest, opts ...grpc.CallOption) (*GetPipelineStatusResponse, error)
	CancelPipeline(ctx context.Context, in *CancelPipelineRequest, opts ...grpc.CallOption) (*CancelPipelineResponse, error)
}

type coordinatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorServiceClient(cc grpc.ClientConnInterface) CoordinatorServiceClient {
	return &coordinatorServiceClient{cc}
}

func (c *coordinatorServiceClient) SubmitPipeline(ctx context.Context, in *SubmitPipelineRequest, opts ...grpc.CallOption) (*SubmitPipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitPipelineResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_SubmitPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) GetPipelineStatus(ctx context.Context, in *GetPipelineStatusRequest, opts ...grpc.CallOption) (*GetPipelineStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPipelineStatusResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_GetPipelineStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) CancelPipeline(ctx context.Context, in *CancelPipelineRequest, opts ...grpc.CallOption) (*CancelPipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelPipelineResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_CancelPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServiceServer is the server API for CoordinatorService service.
// All implementations must embed UnimplementedCoordinatorServiceServer
// for forward compatibility.
//
// CoordinatorService is the external API for the Skewer rendering pipeline.
// Workers communicate directly with Cloud Batch/Workflows, not this service.
type CoordinatorServiceServer interface {
	SubmitPipeline(context.Context, *SubmitPipelineRequest) (*SubmitPipelineResponse, error)
	GetPipelineStatus(context.Context, *GetPipelineStatusRequest) (*GetPipelineStatusResponse, error)
	CancelPipeline(context.Context, *CancelPipelineRequest) (*CancelPipelineResponse, error)
	mustEmbedUnimplementedCoordinatorServiceServer()
}

// UnimplementedCoordinatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorServiceServer struct{}

func (UnimplementedCoordinatorServiceServer) SubmitPipeline(context.Context, *SubmitPipelineRequest) (*SubmitPipelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitPipeline not implemented")
}
func (UnimplementedCoordinatorServiceServer) GetPipelineStatus(context.Context, *GetPipelineStatusRequest) (*GetPipelineStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPipelineStatus not implemented")
}
func (UnimplementedCoordinatorServiceServer) CancelPipeline(context.Context, *CancelPipelineRequest) (*CancelPipelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelPipeline not implemented")
}
func (UnimplementedCoordinatorServiceServer) mustEmbedUnimplementedCoordinatorServiceServer() {}
func (UnimplementedCoordinatorServiceServer) testEmbeddedByValue()                            {}

// UnsafeCoordinatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServiceServer will
// result in compilation errors.
type UnsafeCoordinatorServiceServer interface {
	mustEmbedUnimplementedCoordinatorServiceServer()
}

func RegisterCoordinatorServiceServer(s grpc.ServiceRegistrar, srv CoordinatorServiceServer) {
	// If the following call panics, it indicates UnimplementedCoordinatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinatorService_ServiceDesc, srv)
}

func _CoordinatorService_SubmitPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitPipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).SubmitPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_SubmitPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).SubmitPipeline(ctx, req.(*SubmitPipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_GetPipelineStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipelineStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).GetPipelineStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_GetPipelineStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).GetPipelineStatus(ctx, req.(*GetPipelineStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_CancelPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).CancelPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_CancelPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).CancelPipeline(ctx, req.(*CancelPipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinatorService_ServiceDesc is the grpc.ServiceDesc for CoordinatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.coordinator.v1.CoordinatorService",
	HandlerType: (*CoordinatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitPipeline",
			Handler:    _CoordinatorService_SubmitPipeline_Handler,
		},
		{
			MethodName: "GetPipelineStatus",
			Handler:    _CoordinatorService_GetPipelineStatus_Handler,
		},
		{
			MethodName: "CancelPipeline",
			Handler:    _CoordinatorService_CancelPipeline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/coordinator/v1/coordinator.proto",
}
