// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/coordinator/v1/coordinator.proto

package coordinatorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPipelineStatusResponse_PipelineStatus int32

const (
	GetPipelineStatusResponse_PIPELINE_STATUS_UNSPECIFIED GetPipelineStatusResponse_PipelineStatus = 0
	GetPipelineStatusResponse_PIPELINE_STATUS_RUNNING     GetPipelineStatusResponse_PipelineStatus = 1
	GetPipelineStatusResponse_PIPELINE_STATUS_SUCCEEDED   GetPipelineStatusResponse_PipelineStatus = 2
	GetPipelineStatusResponse_PIPELINE_STATUS_FAILED      GetPipelineStatusResponse_PipelineStatus = 3
	GetPipelineStatusResponse_PIPELINE_STATUS_CANCELLED   GetPipelineStatusResponse_PipelineStatus = 4
)

// Enum value maps for GetPipelineStatusResponse_PipelineStatus.
var (
	GetPipelineStatusResponse_PipelineStatus_name = map[int32]string{
		0: "PIPELINE_STATUS_UNSPECIFIED",
		1: "PIPELINE_STATUS_RUNNING",
		2: "PIPELINE_STATUS_SUCCEEDED",
		3: "PIPELINE_STATUS_FAILED",
		4: "PIPELINE_STATUS_CANCELLED",
	}
	GetPipelineStatusResponse_PipelineStatus_value = map[string]int32{
		"PIPELINE_STATUS_UNSPECIFIED": 0,
		"PIPELINE_STATUS_RUNNING":     1,
		"PIPELINE_STATUS_SUCCEEDED":   2,
		"PIPELINE_STATUS_FAILED":      3,
		"PIPELINE_STATUS_CANCELLED":   4,
	}
)

func (x GetPipelineStatusResponse_PipelineStatus) Enum() *GetPipelineStatusResponse_PipelineStatus {
	p := new(GetPipelineStatusResponse_PipelineStatus)
	*p = x
	return p
}

func (x GetPipelineStatusResponse_PipelineStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetPipelineStatusResponse_PipelineStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_coordinator_v1_coordinator_proto_enumTypes[0].Descriptor()
}

func (GetPipelineStatusResponse_PipelineStatus) Type() protoreflect.EnumType {
	return &file_api_proto_coordinator_v1_coordinator_proto_enumTypes[0]
}

func (x GetPipelineStatusResponse_PipelineStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetPipelineStatusResponse_PipelineStatus.Descriptor instead.
func (GetPipelineStatusResponse_PipelineStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{3, 0}
}

// SubmitPipelineRequest is the scene-first submission request.
// The coordinator downloads scene_uri, parses it, classifies layers as
// static or animated, derives num_frames from the animation block, and
// orchestrates rendering without requiring callers to supply layer metadata.
type SubmitPipelineRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	PipelineId               string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`                                               // Optional; server generates a UUID if empty
	SceneUri                 string                 `protobuf:"bytes,2,opt,name=scene_uri,json=sceneUri,proto3" json:"scene_uri,omitempty"`                                                     // GCS path to root scene.json (e.g. gs://bucket/scenes/scene.json)
	CompositeOutputUriPrefix string                 `protobuf:"bytes,3,opt,name=composite_output_uri_prefix,json=compositeOutputUriPrefix,proto3" json:"composite_output_uri_prefix,omitempty"` // GCS prefix for final composited frames
	EnableCache              bool                   `protobuf:"varint,4,opt,name=enable_cache,json=enableCache,proto3" json:"enable_cache,omitempty"`                                           // Enable content-hash layer caching (default false)
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SubmitPipelineRequest) Reset() {
	*x = SubmitPipelineRequest{}
	mi := &file_api_proto_coordinator_v1_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPipelineRequest) ProtoMessage() {}

func (x *SubmitPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_v1_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPipelineRequest.ProtoReflect.Descriptor instead.
func (*SubmitPipelineRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitPipelineRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *SubmitPipelineRequest) GetSceneUri() string {
	if x != nil {
		return x.SceneUri
	}
	return ""
}

func (x *SubmitPipelineRequest) GetCompositeOutputUriPrefix() string {
	if x != nil {
		return x.CompositeOutputUriPrefix
	}
	return ""
}

func (x *SubmitPipelineRequest) GetEnableCache() bool {
	if x != nil {
		return x.EnableCache
	}
	return false
}

type SubmitPipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPipelineResponse) Reset() {
	*x = SubmitPipelineResponse{}
	mi := &file_api_proto_coordinator_v1_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPipelineResponse) ProtoMessage() {}

func (x *SubmitPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_v1_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPipelineResponse.ProtoReflect.Descriptor instead.
func (*SubmitPipelineResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitPipelineResponse) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

type GetPipelineStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineStatusRequest) Reset() {
	*x = GetPipelineStatusRequest{}
	mi := &file_api_proto_coordinator_v1_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineStatusRequest) ProtoMessage() {}

func (x *GetPipelineStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_v1_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPipelineStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *GetPipelineStatusRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

type GetPipelineStatusResponse struct {
	state           protoimpl.MessageState                   `protogen:"open.v1"`
	Status          GetPipelineStatusResponse_PipelineStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.proto.coordinator.v1.GetPipelineStatusResponse_PipelineStatus" json:"status,omitempty"`
	ErrorMessage    string                                   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LayerOutputs    map[string]string                        `protobuf:"bytes,3,rep,name=layer_outputs,json=layerOutputs,proto3" json:"layer_outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // layer_id -> GCS output prefix
	CompositeOutput string                                   `protobuf:"bytes,4,opt,name=composite_output,json=compositeOutput,proto3" json:"composite_output,omitempty"`                                                                  // GCS prefix of final composited frames
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPipelineStatusResponse) Reset() {
	*x = GetPipelineStatusResponse{}
	mi := &file_api_proto_coordinator_v1_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineStatusResponse) ProtoMessage() {}

func (x *GetPipelineStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_v1_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPipelineStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *GetPipelineStatusResponse) GetStatus() GetPipelineStatusResponse_PipelineStatus {
	if x != nil {
		return x.Status
	}
	return GetPipelineStatusResponse_PIPELINE_STATUS_UNSPECIFIED
}

func (x *GetPipelineStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetPipelineStatusResponse) GetLayerOutputs() map[string]string {
	if x != nil {
		return x.LayerOutputs
	}
	return nil
}

func (x *GetPipelineStatusResponse) GetCompositeOutput() string {
	if x != nil {
		return x.CompositeOutput
	}
	return ""
}

type CancelPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPipelineRequest) Reset() {
	*x = CancelPipelineRequest{}
	mi := &file_api_proto_coordinator_v1_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPipelineRequest) ProtoMessage() {}

func (x *CancelPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_v1_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPipelineRequest.ProtoReflect.Descriptor instead.
func (*CancelPipelineRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *CancelPipelineRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

type CancelPipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPipelineResponse) Reset() {
	*x = CancelPipelineResponse{}
	mi := &file_api_proto_coordinator_v1_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPipelineResponse) ProtoMessage() {}

func (x *CancelPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_coordinator_v1_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPipelineResponse.ProtoReflect.Descriptor instead.
func (*CancelPipelineResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *CancelPipelineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_coordinator_v1_coordinator_proto protoreflect.FileDescriptor

const file_api_proto_coordinator_v1_coordinator_proto_rawDesc = "" +
	"\n" +
	"*api/proto/coordinator/v1/coordinator.proto\x12\x18api.proto.coordinator.v1\"\xb7\x01\n" +
	"\x15SubmitPipelineRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x1b\n" +
	"\tscene_uri\x18\x02 \x01(\tR\bsceneUri\x12=\n" +
	"\x1bcomposite_output_uri_prefix\x18\x03 \x01(\tR\x18compositeOutputUriPrefix\x12!\n" +
	"\fenable_cache\x18\x04 \x01(\bR\venableCache\"9\n" +
	"\x16SubmitPipelineResponse\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\";\n" +
	"\x18GetPipelineStatusRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\"\x9f\x04\n" +
	"\x19GetPipelineStatusResponse\x12Z\n" +
	"\x06status\x18\x01 \x01(\x0e2B.api.proto.coordinator.v1.GetPipelineStatusResponse.PipelineStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12j\n" +
	"\rlayer_outputs\x18\x03 \x03(\v2E.api.proto.coordinator.v1.GetPipelineStatusResponse.LayerOutputsEntryR\flayerOutputs\x12)\n" +
	"\x10composite_output\x18\x04 \x01(\tR\x0fcompositeOutput\x1a?\n" +
	"\x11LayerOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x01\n" +
	"\x0ePipelineStatus\x12\x1f\n" +
	"\x1bPIPELINE_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PIPELINE_STATUS_RUNNING\x10\x01\x12\x1d\n" +
	"\x19PIPELINE_STATUS_SUCCEEDED\x10\x02\x12\x1a\n" +
	"\x16PIPELINE_STATUS_FAILED\x10\x03\x12\x1d\n" +
	"\x19PIPELINE_STATUS_CANCELLED\x10\x04\"8\n" +
	"\x15CancelPipelineRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\"2\n" +
	"\x16CancelPipelineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xfc\x02\n" +
	"\x12CoordinatorService\x12s\n" +
	"\x0eSubmitPipeline\x12/.api.proto.coordinator.v1.SubmitPipelineRequest\x1a0.api.proto.coordinator.v1.SubmitPipelineResponse\x12|\n" +
	"\x11GetPipelineStatus\x122.api.proto.coordinator.v1.GetPipelineStatusRequest\x1a3.api.proto.coordinator.v1.GetPipelineStatusResponse\x12s\n" +
	"\x0eCancelPipeline\x12/.api.proto.coordinator.v1.CancelPipelineRequest\x1a0.api.proto.coordinator.v1.CancelPipelineResponseBIZGgithub.com/skewer-project/skewer/api/proto/coordinator/v1;coordinatorv1b\x06proto3"

var (
	file_api_proto_coordinator_v1_coordinator_proto_rawDescOnce sync.Once
	file_api_proto_coordinator_v1_coordinator_proto_rawDescData []byte
)

func file_api_proto_coordinator_v1_coordinator_proto_rawDescGZIP() []byte {
	file_api_proto_coordinator_v1_coordinator_proto_rawDescOnce.Do(func() {
		file_api_proto_coordinator_v1_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_coordinator_v1_coordinator_proto_rawDesc), len(file_api_proto_coordinator_v1_coordinator_proto_rawDesc)))
	})
	return file_api_proto_coordinator_v1_coordinator_proto_rawDescData
}

var file_api_proto_coordinator_v1_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_coordinator_v1_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_coordinator_v1_coordinator_proto_goTypes = []any{
	(GetPipelineStatusResponse_PipelineStatus)(0), // 0: api.proto.coordinator.v1.GetPipelineStatusResponse.PipelineStatus
	(*SubmitPipelineRequest)(nil),                 // 1: api.proto.coordinator.v1.SubmitPipelineRequest
	(*SubmitPipelineResponse)(nil),                // 2: api.proto.coordinator.v1.SubmitPipelineResponse
	(*GetPipelineStatusRequest)(nil),              // 3: api.proto.coordinator.v1.GetPipelineStatusRequest
	(*GetPipelineStatusResponse)(nil),             // 4: api.proto.coordinator.v1.GetPipelineStatusResponse
	(*CancelPipelineRequest)(nil),                 // 5: api.proto.coordinator.v1.CancelPipelineRequest
	(*CancelPipelineResponse)(nil),                // 6: api.proto.coordinator.v1.CancelPipelineResponse
	nil,                                           // 7: api.proto.coordinator.v1.GetPipelineStatusResponse.LayerOutputsEntry
}
var file_api_proto_coordinator_v1_coordinator_proto_depIdxs = []int32{
	0, // 0: api.proto.coordinator.v1.GetPipelineStatusResponse.status:type_name -> api.proto.coordinator.v1.GetPipelineStatusResponse.PipelineStatus
	7, // 1: api.proto.coordinator.v1.GetPipelineStatusResponse.layer_outputs:type_name -> api.proto.coordinator.v1.GetPipelineStatusResponse.LayerOutputsEntry
	1, // 2: api.proto.coordinator.v1.CoordinatorService.SubmitPipeline:input_type -> api.proto.coordinator.v1.SubmitPipelineRequest
	3, // 3: api.proto.coordinator.v1.CoordinatorService.GetPipelineStatus:input_type -> api.proto.coordinator.v1.GetPipelineStatusRequest
	5, // 4: api.proto.coordinator.v1.CoordinatorService.CancelPipeline:input_type -> api.proto.coordinator.v1.CancelPipelineRequest
	2, // 5: api.proto.coordinator.v1.CoordinatorService.SubmitPipeline:output_type -> api.proto.coordinator.v1.SubmitPipelineResponse
	4, // 6: api.proto.coordinator.v1.CoordinatorService.GetPipelineStatus:output_type -> api.proto.coordinator.v1.GetPipelineStatusResponse
	6, // 7: api.proto.coordinator.v1.CoordinatorService.CancelPipeline:output_type -> api.proto.coordinator.v1.CancelPipelineResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_coordinator_v1_coordinator_proto_init() }
func file_api_proto_coordinator_v1_coordinator_proto_init() {
	if File_api_proto_coordinator_v1_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_coordinator_v1_coordinator_proto_rawDesc), len(file_api_proto_coordinator_v1_coordinator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_coordinator_v1_coordinator_proto_goTypes,
		DependencyIndexes: file_api_proto_coordinator_v1_coordinator_proto_depIdxs,
		EnumInfos:         file_api_proto_coordinator_v1_coordinator_proto_enumTypes,
		MessageInfos:      file_api_proto_coordinator_v1_coordinator_proto_msgTypes,
	}.Build()
	File_api_proto_coordinator_v1_coordinator_proto = out.File
	file_api_proto_coordinator_v1_coordinator_proto_goTypes = nil
	file_api_proto_coordinator_v1_coordinator_proto_depIdxs = nil
}
