// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: coordinator/v1/coordinator.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetJobStatusResponse_JobState int32

const (
	GetJobStatusResponse_JOB_STATE_PENDING_UNSPECIFIED GetJobStatusResponse_JobState = 0
	GetJobStatusResponse_JOB_STATE_RUNNING             GetJobStatusResponse_JobState = 1
	GetJobStatusResponse_JOB_STATE_COMPLETED           GetJobStatusResponse_JobState = 2
	GetJobStatusResponse_JOB_STATE_FAILED              GetJobStatusResponse_JobState = 3
)

// Enum value maps for GetJobStatusResponse_JobState.
var (
	GetJobStatusResponse_JobState_name = map[int32]string{
		0: "JOB_STATE_PENDING_UNSPECIFIED",
		1: "JOB_STATE_RUNNING",
		2: "JOB_STATE_COMPLETED",
		3: "JOB_STATE_FAILED",
	}
	GetJobStatusResponse_JobState_value = map[string]int32{
		"JOB_STATE_PENDING_UNSPECIFIED": 0,
		"JOB_STATE_RUNNING":             1,
		"JOB_STATE_COMPLETED":           2,
		"JOB_STATE_FAILED":              3,
	}
)

func (x GetJobStatusResponse_JobState) Enum() *GetJobStatusResponse_JobState {
	p := new(GetJobStatusResponse_JobState)
	*p = x
	return p
}

func (x GetJobStatusResponse_JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetJobStatusResponse_JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_coordinator_v1_coordinator_proto_enumTypes[0].Descriptor()
}

func (GetJobStatusResponse_JobState) Type() protoreflect.EnumType {
	return &file_coordinator_v1_coordinator_proto_enumTypes[0]
}

func (x GetJobStatusResponse_JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetJobStatusResponse_JobState.Descriptor instead.
func (GetJobStatusResponse_JobState) EnumDescriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{3, 0}
}

type HeartbeatResponse_Command int32

const (
	HeartbeatResponse_COMMAND_CONTINUE_UNSPECIFIED HeartbeatResponse_Command = 0
	HeartbeatResponse_COMMAND_SHUTDOWN             HeartbeatResponse_Command = 1
)

// Enum value maps for HeartbeatResponse_Command.
var (
	HeartbeatResponse_Command_name = map[int32]string{
		0: "COMMAND_CONTINUE_UNSPECIFIED",
		1: "COMMAND_SHUTDOWN",
	}
	HeartbeatResponse_Command_value = map[string]int32{
		"COMMAND_CONTINUE_UNSPECIFIED": 0,
		"COMMAND_SHUTDOWN":             1,
	}
)

func (x HeartbeatResponse_Command) Enum() *HeartbeatResponse_Command {
	p := new(HeartbeatResponse_Command)
	*p = x
	return p
}

func (x HeartbeatResponse_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeartbeatResponse_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_coordinator_v1_coordinator_proto_enumTypes[1].Descriptor()
}

func (HeartbeatResponse_Command) Type() protoreflect.EnumType {
	return &file_coordinator_v1_coordinator_proto_enumTypes[1]
}

func (x HeartbeatResponse_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeartbeatResponse_Command.Descriptor instead.
func (HeartbeatResponse_Command) EnumDescriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{7, 0}
}

type SubmitJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Job data for the requested scene
	SceneFileUri    string `protobuf:"bytes,1,opt,name=scene_file_uri,json=sceneFileUri,proto3" json:"scene_file_uri,omitempty"` // URI to the scene (e.g. .obj or custom manifest)
	Width           int32  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height          int32  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	SamplesPerPixel int32  `protobuf:"varint,4,opt,name=samples_per_pixel,json=samplesPerPixel,proto3" json:"samples_per_pixel,omitempty"`
	MaxDepth        int32  `protobuf:"varint,5,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	// Logical layers requested for this job
	LayerNames []string `protobuf:"bytes,6,rep,name=layer_names,json=layerNames,proto3" json:"layer_names,omitempty"`
	// The base bucket/prefix where all layer files and final output should be stored
	// e.g., "gs://my-bucket/jobs/job_uuid/"
	OutputBaseUri string `protobuf:"bytes,7,opt,name=output_base_uri,json=outputBaseUri,proto3" json:"output_base_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitJobRequest) GetSceneFileUri() string {
	if x != nil {
		return x.SceneFileUri
	}
	return ""
}

func (x *SubmitJobRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *SubmitJobRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *SubmitJobRequest) GetSamplesPerPixel() int32 {
	if x != nil {
		return x.SamplesPerPixel
	}
	return 0
}

func (x *SubmitJobRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *SubmitJobRequest) GetLayerNames() []string {
	if x != nil {
		return x.LayerNames
	}
	return nil
}

func (x *SubmitJobRequest) GetOutputBaseUri() string {
	if x != nil {
		return x.OutputBaseUri
	}
	return ""
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusResponse struct {
	state        protoimpl.MessageState        `protogen:"open.v1"`
	State        GetJobStatusResponse_JobState `protobuf:"varint,1,opt,name=state,proto3,enum=coordinator.v1.GetJobStatusResponse_JobState" json:"state,omitempty"`
	Progress     float32                       `protobuf:"fixed32,2,opt,name=progress,proto3" json:"progress,omitempty"` // 0.0 to 1.0
	ErrorMessage string                        `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// The final composited image URI (only valid if COMPLETED)
	FinalOutputUri string `protobuf:"bytes,4,opt,name=final_output_uri,json=finalOutputUri,proto3" json:"final_output_uri,omitempty"`
	// Status of individual layers
	LayerUris     map[string]string `protobuf:"bytes,5,rep,name=layer_uris,json=layerUris,proto3" json:"layer_uris,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobStatusResponse) GetState() GetJobStatusResponse_JobState {
	if x != nil {
		return x.State
	}
	return GetJobStatusResponse_JOB_STATE_PENDING_UNSPECIFIED
}

func (x *GetJobStatusResponse) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *GetJobStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetJobStatusResponse) GetFinalOutputUri() string {
	if x != nil {
		return x.FinalOutputUri
	}
	return ""
}

func (x *GetJobStatusResponse) GetLayerUris() map[string]string {
	if x != nil {
		return x.LayerUris
	}
	return nil
}

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	CpuCores      int32                  `protobuf:"varint,2,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	WorkerVersion string                 `protobuf:"bytes,3,opt,name=worker_version,json=workerVersion,proto3" json:"worker_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterWorkerRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterWorkerRequest) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *RegisterWorkerRequest) GetWorkerVersion() string {
	if x != nil {
		return x.WorkerVersion
	}
	return ""
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterWorkerResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// Reports status of a worker
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	LoadAverage   float32                `protobuf:"fixed32,2,opt,name=load_average,json=loadAverage,proto3" json:"load_average,omitempty"`
	IsRendering   bool                   `protobuf:"varint,3,opt,name=is_rendering,json=isRendering,proto3" json:"is_rendering,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetLoadAverage() float32 {
	if x != nil {
		return x.LoadAverage
	}
	return 0
}

func (x *HeartbeatRequest) GetIsRendering() bool {
	if x != nil {
		return x.IsRendering
	}
	return false
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Command       HeartbeatResponse_Command `protobuf:"varint,1,opt,name=command,proto3,enum=coordinator.v1.HeartbeatResponse_Command" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_v1_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_v1_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetCommand() HeartbeatResponse_Command {
	if x != nil {
		return x.Command
	}
	return HeartbeatResponse_COMMAND_CONTINUE_UNSPECIFIED
}

var File_coordinator_v1_coordinator_proto protoreflect.FileDescriptor

const file_coordinator_v1_coordinator_proto_rawDesc = "" +
	"\n" +
	" coordinator/v1/coordinator.proto\x12\x0ecoordinator.v1\"\xf8\x01\n" +
	"\x10SubmitJobRequest\x12$\n" +
	"\x0escene_file_uri\x18\x01 \x01(\tR\fsceneFileUri\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12*\n" +
	"\x11samples_per_pixel\x18\x04 \x01(\x05R\x0fsamplesPerPixel\x12\x1b\n" +
	"\tmax_depth\x18\x05 \x01(\x05R\bmaxDepth\x12\x1f\n" +
	"\vlayer_names\x18\x06 \x03(\tR\n" +
	"layerNames\x12&\n" +
	"\x0foutput_base_uri\x18\a \x01(\tR\routputBaseUri\"*\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xcd\x03\n" +
	"\x14GetJobStatusResponse\x12C\n" +
	"\x05state\x18\x01 \x01(\x0e2-.coordinator.v1.GetJobStatusResponse.JobStateR\x05state\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x02R\bprogress\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12(\n" +
	"\x10final_output_uri\x18\x04 \x01(\tR\x0efinalOutputUri\x12R\n" +
	"\n" +
	"layer_uris\x18\x05 \x03(\v23.coordinator.v1.GetJobStatusResponse.LayerUrisEntryR\tlayerUris\x1a<\n" +
	"\x0eLayerUrisEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\bJobState\x12!\n" +
	"\x1dJOB_STATE_PENDING_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x01\x12\x17\n" +
	"\x13JOB_STATE_COMPLETED\x10\x02\x12\x14\n" +
	"\x10JOB_STATE_FAILED\x10\x03\"z\n" +
	"\x15RegisterWorkerRequest\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x1b\n" +
	"\tcpu_cores\x18\x02 \x01(\x05R\bcpuCores\x12%\n" +
	"\x0eworker_version\x18\x03 \x01(\tR\rworkerVersion\"5\n" +
	"\x16RegisterWorkerResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"u\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12!\n" +
	"\fload_average\x18\x02 \x01(\x02R\vloadAverage\x12!\n" +
	"\fis_rendering\x18\x03 \x01(\bR\visRendering\"\x9b\x01\n" +
	"\x11HeartbeatResponse\x12C\n" +
	"\acommand\x18\x01 \x01(\x0e2).coordinator.v1.HeartbeatResponse.CommandR\acommand\"A\n" +
	"\aCommand\x12 \n" +
	"\x1cCOMMAND_CONTINUE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10COMMAND_SHUTDOWN\x10\x012\xf4\x02\n" +
	"\x12CoordinatorService\x12P\n" +
	"\tSubmitJob\x12 .coordinator.v1.SubmitJobRequest\x1a!.coordinator.v1.SubmitJobResponse\x12Y\n" +
	"\fGetJobStatus\x12#.coordinator.v1.GetJobStatusRequest\x1a$.coordinator.v1.GetJobStatusResponse\x12_\n" +
	"\x0eRegisterWorker\x12%.coordinator.v1.RegisterWorkerRequest\x1a&.coordinator.v1.RegisterWorkerResponse\x12P\n" +
	"\tHeartbeat\x12 .coordinator.v1.HeartbeatRequest\x1a!.coordinator.v1.HeartbeatResponseB\x1cZ\x1a./api/proto/coordinator/v1b\x06proto3"

var (
	file_coordinator_v1_coordinator_proto_rawDescOnce sync.Once
	file_coordinator_v1_coordinator_proto_rawDescData []byte
)

func file_coordinator_v1_coordinator_proto_rawDescGZIP() []byte {
	file_coordinator_v1_coordinator_proto_rawDescOnce.Do(func() {
		file_coordinator_v1_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordinator_v1_coordinator_proto_rawDesc), len(file_coordinator_v1_coordinator_proto_rawDesc)))
	})
	return file_coordinator_v1_coordinator_proto_rawDescData
}

var file_coordinator_v1_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_coordinator_v1_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_coordinator_v1_coordinator_proto_goTypes = []any{
	(GetJobStatusResponse_JobState)(0), // 0: coordinator.v1.GetJobStatusResponse.JobState
	(HeartbeatResponse_Command)(0),     // 1: coordinator.v1.HeartbeatResponse.Command
	(*SubmitJobRequest)(nil),           // 2: coordinator.v1.SubmitJobRequest
	(*SubmitJobResponse)(nil),          // 3: coordinator.v1.SubmitJobResponse
	(*GetJobStatusRequest)(nil),        // 4: coordinator.v1.GetJobStatusRequest
	(*GetJobStatusResponse)(nil),       // 5: coordinator.v1.GetJobStatusResponse
	(*RegisterWorkerRequest)(nil),      // 6: coordinator.v1.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil),     // 7: coordinator.v1.RegisterWorkerResponse
	(*HeartbeatRequest)(nil),           // 8: coordinator.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),          // 9: coordinator.v1.HeartbeatResponse
	nil,                                // 10: coordinator.v1.GetJobStatusResponse.LayerUrisEntry
}
var file_coordinator_v1_coordinator_proto_depIdxs = []int32{
	0,  // 0: coordinator.v1.GetJobStatusResponse.state:type_name -> coordinator.v1.GetJobStatusResponse.JobState
	10, // 1: coordinator.v1.GetJobStatusResponse.layer_uris:type_name -> coordinator.v1.GetJobStatusResponse.LayerUrisEntry
	1,  // 2: coordinator.v1.HeartbeatResponse.command:type_name -> coordinator.v1.HeartbeatResponse.Command
	2,  // 3: coordinator.v1.CoordinatorService.SubmitJob:input_type -> coordinator.v1.SubmitJobRequest
	4,  // 4: coordinator.v1.CoordinatorService.GetJobStatus:input_type -> coordinator.v1.GetJobStatusRequest
	6,  // 5: coordinator.v1.CoordinatorService.RegisterWorker:input_type -> coordinator.v1.RegisterWorkerRequest
	8,  // 6: coordinator.v1.CoordinatorService.Heartbeat:input_type -> coordinator.v1.HeartbeatRequest
	3,  // 7: coordinator.v1.CoordinatorService.SubmitJob:output_type -> coordinator.v1.SubmitJobResponse
	5,  // 8: coordinator.v1.CoordinatorService.GetJobStatus:output_type -> coordinator.v1.GetJobStatusResponse
	7,  // 9: coordinator.v1.CoordinatorService.RegisterWorker:output_type -> coordinator.v1.RegisterWorkerResponse
	9,  // 10: coordinator.v1.CoordinatorService.Heartbeat:output_type -> coordinator.v1.HeartbeatResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_coordinator_v1_coordinator_proto_init() }
func file_coordinator_v1_coordinator_proto_init() {
	if File_coordinator_v1_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordinator_v1_coordinator_proto_rawDesc), len(file_coordinator_v1_coordinator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordinator_v1_coordinator_proto_goTypes,
		DependencyIndexes: file_coordinator_v1_coordinator_proto_depIdxs,
		EnumInfos:         file_coordinator_v1_coordinator_proto_enumTypes,
		MessageInfos:      file_coordinator_v1_coordinator_proto_msgTypes,
	}.Build()
	File_coordinator_v1_coordinator_proto = out.File
	file_coordinator_v1_coordinator_proto_goTypes = nil
	file_coordinator_v1_coordinator_proto_depIdxs = nil
}
